services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: simulation_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/simulation_app:/app
    environment:
      - PORT=8080
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_dashboard
    ports:
      - "8081:8081"
    depends_on:
      - backend
    restart: always
